import type { Catalog } from "../schema.js";
import { MenuFile, type MenuFileInput, mergeCatalogs, normalizeMenu } from "../menu-format.js";
import { LocalCatalogAdapter } from "./local.js";

/**
 * Two seeded Halifax businesses for demos and tests:
 * - Crumb & Co, a bakery with lead-time cakes, catering platters and a daily sell-out bun
 * - Northline Coffee, a cafe with full drink modifiers and office catering
 * Stock is "live": as_of is always now.
 */

const GLUTEN = ["wheat", "gluten"] as const;

export const crumbAndCo: MenuFileInput = {
  business: {
    id: "crumb-and-co",
    name: "Crumb & Co",
    type: "bakery",
    currency: "CAD",
    website: "https://crumbandco.example",
    policies: {
      cancellation: { free_within_minutes: 10, until_minutes_before_ready: 720 },
      refund: "Full refund for cancellations inside the window. Custom cakes are non-refundable once decorated.",
      payment: "Pay at pickup, or monthly invoice for business accounts.",
    },
  },
  locations: [
    {
      id: "crumb-quinpool",
      name: "Crumb & Co Quinpool",
      address: {
        line1: "6245 Quinpool Rd",
        city: "Halifax",
        region: "NS",
        postal_code: "B3L 1A3",
        country: "CA",
        lat: 44.6466,
        lng: -63.5961,
      },
      phone: "+1-902-555-0142",
      timezone: "America/Halifax",
      hours: {
        mon: "closed",
        tue: "07:00-18:00",
        wed: "07:00-18:00",
        thu: "07:00-18:00",
        fri: "07:00-19:00",
        sat: "08:00-17:00",
        sun: "08:00-15:00",
      },
      fulfillment: ["pickup", "delivery", "catering"],
      delivery: { radius_km: 5, fee: 5.99, minimum: 30, minutes: 25 },
      prep_minutes: 20,
      tax_rate: 14,
    },
    {
      id: "crumb-hydrostone",
      name: "Crumb & Co Hydrostone",
      address: {
        line1: "5521 Young St",
        city: "Halifax",
        region: "NS",
        postal_code: "B3K 1Z7",
        country: "CA",
        lat: 44.6634,
        lng: -63.6038,
      },
      timezone: "America/Halifax",
      hours: {
        mon: "07:30-16:00",
        tue: "07:30-16:00",
        wed: "07:30-16:00",
        thu: "07:30-16:00",
        fri: "07:30-16:00",
        sat: "08:00-15:00",
        sun: "closed",
      },
      fulfillment: ["pickup", "dine_in"],
      prep_minutes: 10,
      tax_rate: 14,
    },
  ],
  categories: [
    { id: "crumb-pastries", name: "Pastries" },
    { id: "crumb-breads", name: "Breads" },
    { id: "crumb-lunch", name: "Lunch Sandwiches & Bowls" },
    { id: "crumb-sweets", name: "Sweets" },
    { id: "crumb-cakes", name: "Celebration Cakes", description: "Made to order. 48 hours notice." },
    { id: "crumb-catering", name: "Catering" },
    { id: "crumb-drinks", name: "Drinks" },
  ],
  items: [
    {
      id: "crumb-butter-croissant",
      name: "Butter Croissant",
      description: "Laminated over three days with cultured Nova Scotia butter.",
      category: "crumb-pastries",
      price: 3.75,
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg"], may_contain: ["tree_nut", "sesame"] },
      stock: { status: "in_stock", quantity: 40 },
    },
    {
      id: "crumb-almond-croissant",
      name: "Almond Croissant",
      description: "Twice-baked with frangipane and toasted almonds.",
      category: "crumb-pastries",
      price: 4.95,
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg", "tree_nut"], may_contain: ["sesame"] },
      stock: { status: "in_stock", quantity: 18 },
    },
    {
      id: "crumb-morning-bun",
      name: "Cardamom Morning Bun",
      description: "Our cult favourite. Baked once at 7am, gone by mid-morning.",
      category: "crumb-pastries",
      price: 4.5,
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg"], may_contain: ["tree_nut"] },
      stock_by_location: {
        "crumb-quinpool": { status: "low", quantity: 3 },
        "crumb-hydrostone": { status: "sold_out", quantity: 0 },
      },
    },
    {
      id: "crumb-fruit-galette",
      name: "Seasonal Fruit Galette",
      description: "Whatever the Annapolis Valley gave us this week.",
      category: "crumb-pastries",
      price: 5.25,
      dietary: ["vegetarian"],
      // Intentionally no allergen info: agents must see "unknown", never "safe".
      stock: "in_stock",
    },
    {
      id: "crumb-sourdough",
      name: "Country Sourdough Loaf",
      description: "Naturally leavened, 36-hour ferment. Flour, water, salt.",
      category: "crumb-breads",
      price: 9.0,
      dietary: ["vegetarian", "vegan", "dairy_free", "nut_free"],
      allergens: { contains: [...GLUTEN] },
      stock: { status: "in_stock", quantity: 22 },
    },
    {
      id: "crumb-ham-gruyere",
      name: "Ham & Gruyère Baguette",
      description: "Black Forest ham, aged Gruyère, Dijon butter.",
      category: "crumb-lunch",
      price: 12.95,
      role: "main",
      allergens: { contains: [...GLUTEN, "milk", "mustard"], may_contain: ["sesame", "egg"] },
      stock: { status: "in_stock", quantity: 24 },
    },
    {
      id: "crumb-veg-focaccia",
      name: "Roasted Veg & Hummus Focaccia",
      description: "Charred peppers, zucchini, red onion, lemon hummus on rosemary focaccia.",
      category: "crumb-lunch",
      price: 11.95,
      role: "main",
      dietary: ["vegetarian", "vegan", "dairy_free"],
      allergens: { contains: [...GLUTEN, "sesame"], may_contain: ["tree_nut"] },
      stock: { status: "in_stock", quantity: 16 },
    },
    {
      id: "crumb-egg-salad",
      name: "Egg Salad Croissant",
      category: "crumb-lunch",
      price: 10.95,
      role: "main",
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg", "mustard"], may_contain: ["tree_nut"] },
      stock: { status: "in_stock", quantity: 12 },
    },
    {
      id: "crumb-chicken-pesto",
      name: "Chicken Pesto Ciabatta",
      description: "Roast chicken, basil-pine nut pesto, arugula, provolone.",
      category: "crumb-lunch",
      price: 13.95,
      role: "main",
      allergens: { contains: [...GLUTEN, "milk", "tree_nut"], may_contain: ["sesame"] },
      stock: { status: "in_stock", quantity: 14 },
    },
    {
      id: "crumb-quinoa-bowl",
      name: "Gluten-Free Quinoa Bowl",
      description: "Quinoa, roasted squash, kale, feta, maple-cider vinaigrette. Prepared in a bakery that handles wheat.",
      category: "crumb-lunch",
      price: 13.95,
      role: "main",
      dietary: ["vegetarian", "gluten_free", "nut_free"],
      allergens: { contains: ["milk"], may_contain: [...GLUTEN] },
      stock: { status: "in_stock", quantity: 8 },
    },
    {
      id: "crumb-chocolate-chip-cookie",
      name: "Brown Butter Chocolate Chip Cookie",
      category: "crumb-sweets",
      price: 3.25,
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg", "soy"], may_contain: ["peanut", "tree_nut"] },
      stock: { status: "in_stock", quantity: 36 },
    },
    {
      id: "crumb-lemon-polenta",
      name: "Lemon Polenta Cake Slice",
      category: "crumb-sweets",
      price: 5.5,
      dietary: ["vegetarian", "gluten_free"],
      allergens: { contains: ["milk", "egg", "tree_nut"], may_contain: [...GLUTEN] },
      stock: { status: "in_stock", quantity: 10 },
    },
    {
      id: "crumb-chocolate-cake",
      name: "Chocolate Celebration Cake (8 in)",
      description: "Dark chocolate sponge, salted caramel, ganache. Custom inscription included.",
      category: "crumb-cakes",
      price: 58.0,
      role: "dessert",
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg", "soy"], may_contain: ["tree_nut", "peanut"] },
      lead_time: "48h",
      serves: 12,
      only_for: ["pickup", "delivery", "catering"],
      locations: ["crumb-quinpool"],
      modifiers: [
        {
          id: "inscription",
          name: "Inscription",
          min: 0,
          max: 1,
          options: [
            { id: "happy-birthday", name: "Happy Birthday", price: 0 },
            { id: "congratulations", name: "Congratulations", price: 0 },
            { id: "custom", name: "Custom message (add in notes)", price: 0 },
          ],
        },
        {
          id: "candles",
          name: "Candles",
          min: 0,
          max: 1,
          options: [{ id: "candles", name: "Box of 24 candles", price: 3.0 }],
        },
      ],
      stock: "in_stock",
    },
    {
      id: "crumb-lemon-chiffon",
      name: "Lemon Chiffon Cake (6 in)",
      category: "crumb-cakes",
      price: 42.0,
      role: "dessert",
      dietary: ["vegetarian", "nut_free"],
      allergens: { contains: [...GLUTEN, "milk", "egg"] },
      lead_time: "48h",
      serves: 8,
      locations: ["crumb-quinpool"],
      stock: "in_stock",
    },
    {
      id: "crumb-sandwich-platter",
      name: "Sandwich Platter (serves 10)",
      description: "20 half sandwiches: ham & gruyère, egg salad, roasted veg. Labelled by filling.",
      category: "crumb-catering",
      price: 119.0,
      role: "main",
      allergens: { contains: [...GLUTEN, "milk", "egg", "mustard", "sesame"], may_contain: ["tree_nut"] },
      lead_time: "24h",
      serves: 10,
      only_for: ["catering", "delivery", "pickup"],
      locations: ["crumb-quinpool"],
      stock: "in_stock",
    },
    {
      id: "crumb-pastry-box",
      name: "Morning Pastry Box (serves 12)",
      description: "Croissants, pain au chocolat, and seasonal danishes.",
      category: "crumb-catering",
      price: 48.0,
      role: "dessert",
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg"], may_contain: ["tree_nut", "sesame"] },
      lead_time: "2h",
      serves: 12,
      locations: ["crumb-quinpool"],
      stock: "in_stock",
    },
    {
      id: "crumb-drip-coffee",
      name: "Drip Coffee",
      description: "Rotating single-origin from a Halifax roaster. Milk and oat milk at the counter.",
      category: "crumb-drinks",
      price: 3.0,
      dietary: ["vegan", "vegetarian", "gluten_free", "dairy_free", "nut_free"],
      allergens: { may_contain: ["milk"] },
      stock: "in_stock",
    },
    {
      id: "crumb-apple-cider",
      name: "Sparkling Valley Apple Cider",
      description: "Non-alcoholic, pressed in the Annapolis Valley.",
      category: "crumb-drinks",
      price: 2.75,
      dietary: ["vegan", "vegetarian", "gluten_free", "dairy_free", "nut_free"],
      allergens: { contains: ["sulphites"] },
      stock: { status: "in_stock", quantity: 48 },
    },
  ],
  stock_updated_at: "live",
  stock_ttl_seconds: 300,
};

const SIZE = {
  id: "size",
  name: "Size",
  min: 1,
  max: 1,
  options: [
    { id: "small", name: "Small 12oz", price: 0 },
    { id: "medium", name: "Medium 16oz", price: 0.75 },
    { id: "large", name: "Large 20oz", price: 1.25 },
  ],
};
const MILK = {
  id: "milk",
  name: "Milk",
  min: 1,
  max: 1,
  options: [
    { id: "whole", name: "Whole milk", price: 0 },
    { id: "skim", name: "Skim milk", price: 0 },
    { id: "oat", name: "Oat milk", price: 0.75 },
    { id: "almond", name: "Almond milk", price: 0.75 },
    { id: "soy", name: "Soy milk", price: 0.5 },
  ],
};
const SHOTS = {
  id: "extra-shot",
  name: "Extra espresso",
  min: 0,
  max: 1,
  options: [
    { id: "one", name: "+1 shot", price: 1.25 },
    { id: "two", name: "+2 shots", price: 2.5 },
  ],
};
const SYRUP = {
  id: "syrup",
  name: "Syrup",
  min: 0,
  max: 2,
  options: [
    { id: "vanilla", name: "Vanilla", price: 0.75 },
    { id: "caramel", name: "Caramel", price: 0.75 },
    { id: "maple", name: "Nova Scotia maple", price: 0.95 },
  ],
};
const TEMP = {
  id: "temperature",
  name: "Temperature",
  min: 1,
  max: 1,
  options: [
    { id: "hot", name: "Hot", price: 0 },
    { id: "iced", name: "Iced", price: 0 },
  ],
};

export const northlineCoffee: MenuFileInput = {
  business: {
    id: "northline-coffee",
    name: "Northline Coffee",
    type: "cafe",
    currency: "CAD",
    website: "https://northline.example",
    policies: {
      cancellation: { free_within_minutes: 5, until_minutes_before_ready: 60 },
      refund: "Refunds for cancelled orders within 3 business days. Quality issues: reply to your receipt and we make it right.",
      payment: "Pay at pickup, or on account (net 30 invoice) for office customers.",
    },
  },
  locations: [
    {
      id: "northline-barrington",
      name: "Northline Coffee Barrington",
      address: {
        line1: "1650 Barrington St",
        city: "Halifax",
        region: "NS",
        postal_code: "B3J 2A1",
        country: "CA",
        lat: 44.6455,
        lng: -63.5747,
      },
      phone: "+1-902-555-0187",
      timezone: "America/Halifax",
      hours: {
        mon: "07:00-18:00",
        tue: "07:00-18:00",
        wed: "07:00-18:00",
        thu: "07:00-18:00",
        fri: "07:00-18:00",
        sat: "08:00-17:00",
        sun: "08:00-17:00",
      },
      fulfillment: ["pickup", "delivery", "catering", "dine_in"],
      delivery: { postal_codes: ["B3H", "B3J", "B3K", "B3L", "B3M"], fee: 4.99, minimum: 25, minutes: 25 },
      prep_minutes: 15,
      tax_rate: 14,
    },
    {
      id: "northline-dartmouth",
      name: "Northline Coffee Dartmouth Waterfront",
      address: {
        line1: "88 Alderney Dr",
        city: "Dartmouth",
        region: "NS",
        postal_code: "B2Y 2N4",
        country: "CA",
        lat: 44.6658,
        lng: -63.5672,
      },
      timezone: "America/Halifax",
      hours: {
        mon: "06:30-16:00",
        tue: "06:30-16:00",
        wed: "06:30-16:00",
        thu: "06:30-16:00",
        fri: "06:30-16:00",
        sat: "08:00-15:00",
        sun: "08:00-15:00",
      },
      fulfillment: ["pickup", "dine_in"],
      prep_minutes: 10,
      tax_rate: 14,
    },
  ],
  categories: [
    { id: "nl-espresso", name: "Espresso & Coffee" },
    { id: "nl-tea", name: "Tea & Not Coffee" },
    { id: "nl-lunch", name: "Lunch" },
    { id: "nl-bakery", name: "Bakery" },
    { id: "nl-catering", name: "Office Catering" },
  ],
  items: [
    {
      id: "nl-latte",
      name: "Latte",
      category: "nl-espresso",
      price: 5.25,
      dietary: ["vegetarian", "gluten_free"],
      allergens: { contains: ["milk"] },
      modifiers: [SIZE, MILK, TEMP, SHOTS, SYRUP],
      stock: "in_stock",
    },
    {
      id: "nl-cappuccino",
      name: "Cappuccino",
      category: "nl-espresso",
      price: 4.95,
      dietary: ["vegetarian", "gluten_free"],
      allergens: { contains: ["milk"] },
      modifiers: [SIZE, MILK, SHOTS],
      stock: "in_stock",
    },
    {
      id: "nl-americano",
      name: "Americano",
      category: "nl-espresso",
      price: 3.75,
      dietary: ["vegan", "vegetarian", "gluten_free", "dairy_free", "nut_free"],
      allergens: { may_contain: ["milk"] },
      modifiers: [SIZE, TEMP, SHOTS],
      stock: "in_stock",
    },
    {
      id: "nl-cold-brew",
      name: "Cold Brew",
      category: "nl-espresso",
      price: 4.95,
      dietary: ["vegan", "vegetarian", "gluten_free", "dairy_free", "nut_free"],
      allergens: { may_contain: ["milk"] },
      modifiers: [SIZE, SYRUP],
      stock: { status: "low", quantity: 9 },
    },
    {
      id: "nl-chai",
      name: "Chai Latte",
      category: "nl-tea",
      price: 5.25,
      dietary: ["vegetarian", "gluten_free"],
      allergens: { contains: ["milk"] },
      modifiers: [SIZE, MILK, TEMP],
      stock: "in_stock",
    },
    {
      id: "nl-matcha",
      name: "Matcha Latte",
      category: "nl-tea",
      price: 5.75,
      dietary: ["vegetarian", "gluten_free"],
      allergens: { contains: ["milk"] },
      modifiers: [SIZE, MILK, TEMP, SYRUP],
      stock: "in_stock",
    },
    {
      id: "nl-sparkling-lemonade",
      name: "Sparkling Lemonade",
      category: "nl-tea",
      price: 3.5,
      dietary: ["vegan", "vegetarian", "gluten_free", "dairy_free", "nut_free"],
      allergens: { contains: ["sulphites"] },
      stock: { status: "in_stock", quantity: 40 },
    },
    {
      id: "nl-turkey-club",
      name: "Turkey Club",
      description: "Roast turkey, bacon, tomato, lettuce, garlic aioli on toasted multigrain.",
      category: "nl-lunch",
      price: 12.95,
      role: "main",
      allergens: { contains: [...GLUTEN, "egg", "mustard"], may_contain: ["sesame", "soy"] },
      stock: { status: "in_stock", quantity: 20 },
    },
    {
      id: "nl-caprese-panini",
      name: "Caprese Panini",
      description: "Fresh mozzarella, tomato, basil pesto, balsamic on ciabatta.",
      category: "nl-lunch",
      price: 11.95,
      role: "main",
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "tree_nut"], may_contain: ["sesame"] },
      stock: { status: "in_stock", quantity: 14 },
    },
    {
      id: "nl-falafel-wrap",
      name: "Falafel Wrap",
      description: "Crispy falafel, tahini, pickled turnip, cucumber, tomato.",
      category: "nl-lunch",
      price: 11.5,
      role: "main",
      dietary: ["vegetarian", "vegan", "dairy_free", "nut_free"],
      allergens: { contains: [...GLUTEN, "sesame"], may_contain: ["soy"] },
      stock: { status: "in_stock", quantity: 12 },
    },
    {
      id: "nl-chicken-caesar-wrap",
      name: "Chicken Caesar Wrap",
      category: "nl-lunch",
      price: 12.5,
      role: "main",
      allergens: { contains: [...GLUTEN, "milk", "egg", "fish", "mustard"] },
      stock: { status: "in_stock", quantity: 18 },
    },
    {
      id: "nl-harvest-bowl",
      name: "Harvest Grain Bowl",
      description: "Wild rice, roasted beets, chickpeas, greens, maple-tahini dressing. Certified gluten-free kitchen station.",
      category: "nl-lunch",
      price: 13.5,
      role: "main",
      dietary: ["vegetarian", "vegan", "gluten_free", "dairy_free", "nut_free"],
      allergens: { contains: ["sesame"] },
      stock: { status: "in_stock", quantity: 10 },
    },
    {
      id: "nl-soup",
      name: "Soup of the Day",
      description: "Rotates daily. Ask the store or check allergens before ordering.",
      category: "nl-lunch",
      price: 7.5,
      role: "side",
      stock: { status: "low", quantity: 5 },
    },
    {
      id: "nl-blueberry-muffin",
      name: "Wild Blueberry Muffin",
      category: "nl-bakery",
      price: 3.95,
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg"], may_contain: ["tree_nut"] },
      stock: { status: "in_stock", quantity: 20 },
    },
    {
      id: "nl-gf-banana-bread",
      name: "Gluten-Free Banana Bread",
      category: "nl-bakery",
      price: 4.25,
      dietary: ["vegetarian", "gluten_free"],
      allergens: { contains: ["egg", "milk"], may_contain: ["tree_nut"] },
      stock: { status: "low", quantity: 4 },
    },
    {
      id: "nl-oat-cookie",
      name: "Oatmeal Date Cookie",
      category: "nl-bakery",
      price: 2.75,
      role: "dessert",
      dietary: ["vegetarian", "vegan", "dairy_free"],
      allergens: { contains: [...GLUTEN], may_contain: ["tree_nut", "peanut"] },
      stock: { status: "in_stock", quantity: 30 },
    },
    {
      id: "nl-coffee-traveler",
      name: "Coffee Traveler (serves 10)",
      description: "96oz of house drip with cups, milk, oat milk and sugar.",
      category: "nl-catering",
      price: 29.95,
      role: "drink",
      dietary: ["vegan", "vegetarian", "gluten_free", "dairy_free", "nut_free"],
      allergens: { may_contain: ["milk"] },
      lead_time: "1h",
      serves: 10,
      only_for: ["delivery", "catering", "pickup"],
      locations: ["northline-barrington"],
      stock: "in_stock",
    },
    {
      id: "nl-sandwich-tray",
      name: "Sandwich Tray (serves 8)",
      description: "Mixed tray of turkey club, caprese and falafel halves.",
      category: "nl-catering",
      price: 89.0,
      role: "main",
      allergens: { contains: [...GLUTEN, "milk", "egg", "sesame", "tree_nut", "mustard"] },
      lead_time: "4h",
      serves: 8,
      only_for: ["delivery", "catering", "pickup"],
      locations: ["northline-barrington"],
      stock: "in_stock",
    },
    {
      id: "nl-pastry-platter",
      name: "Breakfast Pastry Platter (serves 12)",
      category: "nl-catering",
      price: 45.0,
      role: "dessert",
      dietary: ["vegetarian"],
      allergens: { contains: [...GLUTEN, "milk", "egg"], may_contain: ["tree_nut"] },
      lead_time: "2h",
      serves: 12,
      locations: ["northline-barrington"],
      stock: "in_stock",
    },
  ],
  stock_updated_at: "live",
  stock_ttl_seconds: 300,
};

export function mockCatalog(): Catalog {
  // Parse fresh copies so tests that mutate stock never leak into each other.
  return mergeCatalogs(
    normalizeMenu(MenuFile.parse(structuredClone(crumbAndCo))),
    normalizeMenu(MenuFile.parse(structuredClone(northlineCoffee))),
  );
}

export class MockAdapter extends LocalCatalogAdapter {
  override readonly name = "mock";
  constructor(opts: { now?: () => Date } = {}) {
    super(mockCatalog(), opts);
  }
}
